import { Workflow } from './parser';
import { ErrorObject } from 'ajv';

// Type definition for the standalone validator function generated by Ajv
declare const validateWorkflow: ((data: Workflow | unknown) => data is Workflow) & {
  errors?: ErrorObject[] | null;
};

export default validateWorkflow; 